"""add_lat_lng_to_merchant_requests

Revision ID: 09a1a3fa9b0b
Revises: 1520d1a7b0f0
Create Date: 2026-07-04 10:29:39.440881
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a1a3fa9b0b'
down_revision = '1520d1a7b0f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_restaurant_requests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('merchant_restaurant_requests', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_restaurant_requests', 'longitude')
    op.drop_column('merchant_restaurant_requests', 'latitude')
    # ### end Alembic commands ###
