"""Consolidate reviews

Revision ID: 5f3c4070b994
Revises: 20260708_000002
Create Date: 2026-07-09 04:48:02.547669
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f3c4070b994'
down_revision = '20260708_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_reviews_restaurant_id'), table_name='merchant_reviews')
    op.drop_index(op.f('ix_merchant_reviews_user_id'), table_name='merchant_reviews')
    op.drop_table('merchant_reviews')
    op.alter_column('featured_videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('featured_videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_featured_videos_sort_order'), table_name='featured_videos')
    op.add_column('restaurant_reviews', sa.Column('merchant_reply', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_reviews', 'merchant_reply')
    op.create_index(op.f('ix_featured_videos_sort_order'), 'featured_videos', ['sort_order'], unique=False)
    op.alter_column('featured_videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('featured_videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_table('merchant_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('merchant_reply', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_merchant_review_rating')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('merchant_reviews_restaurant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('merchant_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('merchant_reviews_pkey'))
    )
    op.create_index(op.f('ix_merchant_reviews_user_id'), 'merchant_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_merchant_reviews_restaurant_id'), 'merchant_reviews', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###
