"""Add merchandising models

Revision ID: 804d2c11c0a0
Revises: d92604b31ada
Create Date: 2026-07-02 17:16:01.819193
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804d2c11c0a0'
down_revision = 'd92604b31ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('placement', sa.Enum('home_carousel', 'home_banner', name='promoplacement'), nullable=False),
    sa.Column('target_type', sa.Enum('restaurant', 'category', 'menu_item', 'url', 'none', name='promotargettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_banners')
    # ### end Alembic commands ###
