"""add_image_url_mobile

Revision ID: acf0ecbbc747
Revises: 09a1a3fa9b0b
Create Date: 2026-07-04 11:18:43.550106
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf0ecbbc747'
down_revision = '09a1a3fa9b0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_banners', sa.Column('image_url_mobile', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_banners', 'image_url_mobile')
    # ### end Alembic commands ###
